<?php

declare(strict_types=1);

namespace App\Command;

use App\Fetcher\ProviderExecutor;
use App\Provider\ProviderResolver;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

final class ListProvidersCommand extends Command
{
    protected static $defaultName = 'providers:list';

    /**
     * @var ProviderExecutor
     */
    private $executer;

    /**
     * @var ProviderResolver
     */
    private $resolver;

    public function __construct(ProviderResolver $resolver)
    {
        $this->executer = new ProviderExecutor();
        parent::__construct();
        $this->resolver = $resolver;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $io = new SymfonyStyle($input, $output);

        $io->success('test');
    }
}
