services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Provider\ProviderResolver:

  App\Fetcher\ProviderExecutor:

  Symfony\Component\Console\Application:

  App\Command\ListProvidersCommand:
    arguments:
      - '@App\Provider\ProviderResolver'

    tags:
      - { name: 'console.command'}

  App\Command\SearchProvidersCommand:
    tags:
      - { name: 'console.command'}

  shell.console:
    public: true
    alias: Symfony\Component\Console\Application

  App\Provider\NullProvider:
    tags:
      - { name: exchanges.provider }

  App\Provider\AnotherProvider:
    tags:
      - { name: exchanges.provider }

