services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kefzce\CryptoCurrencyExchanges\Provider\ProviderResolver:

  Kefzce\CryptoCurrencyExchanges\Fetcher\ProviderExecutor:

  Symfony\Component\Console\Application:

  Kefzce\CryptoCurrencyExchanges\Command\ListProvidersCommand:
    arguments:
      - '@Kefzce\CryptoCurrencyExchanges\Provider\ProviderResolver'
    tags:
      - { name: 'console.command', command: 'providers:list' }

  Kefzce\CryptoCurrencyExchanges\Command\SearchProvidersCommand:
    arguments:
      - '@Kefzce\CryptoCurrencyExchanges\Provider\ProviderResolver'
    tags:
      - { name: 'console.command', command: 'provider:search' }

  shell.console:
    public: true
    alias: Symfony\Component\Console\Application

  Kefzce\CryptoCurrencyExchanges\Provider\NullProvider:
    public: true
    tags:
      - { name: exchanges.provider }

  Kefzce\CryptoCurrencyExchanges\Provider\AnotherProvider:
    public: true
    tags:
      - { name: exchanges.provider }

  Kefzce\CryptoCurrencyExchanges\Http\ClientBuilder:

#  http.client:
#    class: '@Kefzce\CryptoCurrencyExchanges\Http\ClientBuilder'
#    factory:   'Kefzce\CryptoCurrencyExchangesHttp\ClientBuilder:build'