services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: false

  Kefzce\CryptoCurrencyExchanges\Provider\ProviderResolver:
      public: true

  provider.resolver:
      class: Kefzce\CryptoCurrencyExchanges\Provider\ProviderResolver
      public: true

  Symfony\Component\Console\Application:
      public: true

  shell.console:
      alias: Symfony\Component\Console\Application
      public: true

  Kefzce\CryptoCurrencyExchanges\Command\ListProvidersCommand:
      arguments:
        - '@provider.resolver'
      tags:
        - { name: 'console.command', command: 'providers:list' }

  Kefzce\CryptoCurrencyExchanges\Command\SearchProvidersCommand:
      arguments:
        - '@provider.resolver'
      tags:
        - { name: 'console.command', command: 'provider:search' }

  Kefzce\CryptoCurrencyExchanges\Provider\ProviderBuilder:
      alias: provider.builder
      public: true

  provider.builder:
      class: Kefzce\CryptoCurrencyExchanges\Provider\ProviderBuilder
      public: true
      arguments:
        - '@service_container'

  Kefzce\CryptoCurrencyExchanges\Http\ClientBuilder:

  Kefzce\CryptoCurrencyExchanges\Provider\NullProvider:
      public: true
      tags:
        - { name: exchanges.provider }

  http.transport:
      class: Kefzce\CryptoCurrencyExchanges\Http\ClientBuilder
      factory: 'Kefzce\CryptoCurrencyExchanges\Http\ClientBuilder:build'

  Kefzce\CryptoCurrencyExchanges\Provider\HttpClient:
      arguments:
        - '@http.transport'

  http.client:
      class: Kefzce\CryptoCurrencyExchanges\Provider\Coinbase\HttpClient
      arguments:
        - '@http.transport'

  Kefzce\CryptoCurrencyExchanges\Validator\Validator:
      public: false

  Kefzce\CryptoCurrencyExchanges\Serializer\SerializerFactory:
    public: false

  custom.validator:
      class: Kefzce\CryptoCurrencyExchanges\Validator\Validator
      factory: 'Kefzce\CryptoCurrencyExchanges\Validator\Validator:create'

  custom.serializer:
      class: Kefzce\CryptoCurrencyExchanges\Converter\SerializerFactory
      factory: 'Kefzce\CryptoCurrencyExchanges\Serializer\SerializerFactory:createSerializer'

  object.converter:
      class: Kefzce\CryptoCurrencyExchanges\Converter\ObjectConverter
      arguments:
        - "@=container.has('serializer') ? service('serializer') : service('custom.serializer')"
        - "@=container.has('validator') ? service('validator') : service('custom.validator')"

  Kefzce\CryptoCurrencyExchanges\Provider\Coinbase\CoinbaseProvider:
      arguments:
        - '@http.client'
        - '@object.converter'
      public: true
      tags:
        - { name: exchanges.provider }
